version: '3.8'
services:

  pgdb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clipgear
    ports:
      - '5432:5432'
    volumes: 
      - pgdb_v:/var/lib/postgresql/data
  
  be_dev:
    build: 
      context: .
      dockerfile: ./dockerfile.dev
    environment:
      - PGSQL_HOST=pgdb
      - PGSQL_USERNAME=postgres
      - PGSQL_PASSWORD=postgres
    ports:
      - '8899:8899'

  be_test:
    build: 
      context: .
      dockerfile: ./dockerfile.dev.test
    volumes:
      - ".:/app"

volumes:
  pgdb_v:
    