version: '3.8'
services:

  pgdb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clipgear
    ports:
      - '5432:5432'
    volumes: 
      - pgdb_v:/var/lib/postgresql/data

  be_dev_debug:
    build: 
      context: .
      dockerfile: ./dockerfile.dev.debug
    environment:
      - PGSQL_HOST=pgdb
      - PGSQL_USERNAME=postgres
      - PGSQL_PASSWORD=postgres
    volumes:
      - .:/app
    ports:
      - '8898:8898'
      - '8899:8899'

  be_test_debug:
    build: 
      context: .
      dockerfile: ./dockerfile.dev.test.debug
    volumes:
      - ".:/app"
    ports:
      - '8897:8897'

volumes:
  pgdb_v:
    