version: '3.8'
services:

  be_dev_debug:
    build: 
      context: .
      dockerfile: ./dockerfile.dev.debug
    environment:
      - PGSQL_HOST=pgdb
      - PGSQL_USERNAME=postgres
      - PGSQL_PASSWORD=postgres
    volumes:
      - .:/app
    ports:
      - '8898:8898'
      - '8899:8899'

  be_test_debug:
    build: 
      context: .
      dockerfile: ./dockerfile.dev.test.debug
    volumes:
      - ".:/app"
    ports:
      - '8897:8897'